### PR TITLE
V1.2 Add support for ExpiryDate and Type as fields for Ingredient

### LINKED ISSUE #35: Add ExpiryDate and Type fields support for Ingredient

### PR DESCRIPTION
**Pull request by NayLin-H99**
Fixes #35

### CODE REVIEW

**Comment by rootkie** [comment]
I think the `isSameIngredient` method should be modified to matching `name, type, expiry date`. 

For adding new ingredient, if a same ingredient is added, the quantity should be increased instead of rejected.

**Comment by rebeccacxy** [comment]
@rootkie 
> For adding new ingredient, if a same ingredient is added, the quantity should be increased instead of rejected. Since quantity is yet to be implemented, I think this can be done in the PR that is adding the quantity field.

What happens to the other fields (`description` and `tags`) of the new and existing ingredient? When you check based on `name, type, expiry` then combine based on that equality, are tags combined as well? What about description?

**Comment by rootkie** [comment]
> 
> 
> @rootkie
> 
> > For adding new ingredient, if a same ingredient is added, the quantity should be increased instead of rejected. Since quantity is yet to be implemented, I think this can be done in the PR that is adding the quantity field.
> 
> What happens to the other fields (`description` `tags` `type`) of the new and existing ingredient? Since this is basically a `combine` operation, when you check based on `name, type, expiry` then combine based on that equality, are tags combined as well? What about description?
> 
> Idk if this is a good idea and the `edit` command might be better for this.

That's a good point. I am thinking more about the complexity invovled when recipe is executed, which ingredient should be consumed. This will have a direct impact on how we define the identity of ingredients. I think we can discuss this further during meeting.

**Comment by rebeccacxy** [comment]
@rootkie 
> That's a good point. I am thinking more about the complexity invovled when recipe is executed, which ingredient should be consumed. This will have a direct impact on how we define the identity of ingredients. I think we can discuss this further during meeting.

For simplicity I suggest `isSameIngredient` only checks based on `name`, reject duplicates based on `name`. If the user wants 2 apples with different expiry then they can name it differently.
So recipe is just executed based on `name` and `quantity`.

**Comment by alissayarmantho** [comment]
> @rootkie
> 
> > That's a good point. I am thinking more about the complexity invovled when recipe is executed, which ingredient should be consumed. This will have a direct impact on how we define the identity of ingredients. I think we can discuss this further during meeting.
> 
> For simplicity I suggest `isSameIngredient` only checks based on `name`, reject duplicates based on `name`. If the user wants 2 apples with different expiry then they can name it differently. So recipe is just executed based on `name` and `quantity`.

I'm not so sure on what could be a solution for the combination of `description`, `tag` and `type`, but I think if we check based on `name`, then we will have a different problem: eg. users being forced to name their apple with like apple, apple 2, even though they r the same apples with different expiry. And then recipe consumption which only consumes apple will not be able to consume apple 2.

**Comment by rebeccacxy** [comment]
> I'm not so sure on what could be a solution for the combination of `description`, `tag` and `type`, but I think if we check based on `name`, then we will have a different problem: eg. users being forced to name their apple with like apple, apple 2, even though they r the same apples with different expiry. And then recipe consumption which only consumes apple will not be able to consume apple 2.

I dont see an issue with that actually. `apple new` `apple old` is fine to me, anyway how many identical apples with different expiries will someone buy? Unless they are hoarding apples.
Recipe consumption will treat them as 2 different items. The user can split the quantity of apples themselves.

**Comment by rebeccacxy** [comment]
> I'm not so sure on what could be a solution for the combination of `description`, `tag` and `type`, but I think if we check based on `name`, then we will have a different problem: eg. users being forced to name their apple with like apple, apple 2, even though they r the same apples with different expiry. And then recipe consumption which only consumes apple will not be able to consume apple 2.

The user can edit the recipe to split the quantity amongst the different apples. Either way that will be a user issue and not a bug on our side, since they are treated as 2 different items.

**Pull request merged**
