### PR TITLE
Edit comparison to allow for case-insensitive comparison of ingredients and recipes

### LINKED ISSUE #188: [PE-D] Duplicate inputs
There are the same ingredients but with capital letters instead.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: driip-ddrop/ped#15

### PR DESCRIPTION
**Pull request by pattan9955**
Fixes #188

### CODE REVIEW

**Comment by alissayarmantho** [comment]
Wait I thought what it means is allowing the same name ingredient to be added w diff expiry dates. This one is not allowing same name ingredient right?

**Comment by rootkie** [comment]
Should probably resolve conflict with the recently merged expiry date as part of weaker equality. Also update the javadoc for isSameIngredient when resolving the conflict.

**Review by rootkie — APPROVED** [review]
LGTM

**Review by rebeccacxy — APPROVED** [review]
LGTM

**Pull request merged**
